function(MinMaxOption Name Default Min Max DocString Advanced)
  set(${Name} ${Default} CACHE STRING ${DocString})
  if (Advanced)
    mark_as_advanced(${Name})
  endif (Advanced)
  if ((${Name} LESS ${Min}) OR (${Name} GREATER ${Max}))
    set(${Name} ${Default} CACHE STRING ${DocString} FORCE)
    message(FATAL_ERROR "${Name} must be >= ${Min} and <= ${Max}")
  endif ((${Name} LESS ${Min}) OR (${Name} GREATER ${Max}))
endfunction()
